name: controle_financeiro
description: Controle financeiro para advogados.

publish_to: 'none' # Remove this line if you plan to publish your package

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'  # Use your desired SDK version range

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

  # Your other dependencies here
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
